seed: 42
num_workers : 4

model_name   : 'sgaligner'
modules      : ['pct', 'gat', 'rel', 'attr']
registration : True

data :
  name            : Scan3R
  root_dir        : /media/sayan/internal1/datasets/Scan3R/
  subscan_dir      : /drive/dumps/sgaligner/subscans/Scan3R

preprocess :
  pc_resolutions      : [512]
  subscenes_per_scene : 7
  min_obj_points      : 50
  anchor_type_name    : '_subscan_anchors_w_wo_overlap' 